### ISSUE TITLE
Bylaws draft

### ISSUE THREAD

**Issue by hardkano** [hardkano/Governance#2]
Please comments **bylaws.md** early draft here so we can work it around the communitty needs.

**Comment by wizd** [comment]
Is this a misunderstanding? we need a foundation for Lyra, not a foundation for Graft. 

Lyra needs to run standalone. Graft needs to run standalone, either, Not only for now but also for the future. If you mix both, that will be horrible complexity beyond our ability. KISS, or keep it simple stupid, is the motto of the IT industry.

**Comment by hardkano** [comment]
If the plan is to swap GRFT coins into LYRA gas token, then both are tied. 1 Project, 2 products. 1 being the evolution product of the other including loyalty. Both have the same goal. Payment industry at large scale with loyalty platform. As planned in the roadmap. Let wait what Dan have to say about it. He is the Founder after all. In all respect, if LYRA fork and separate from GRAFT the communitty won't follow. It will be another project in the depth of the crypto winter. The key aspect here is a transition for the GRAFT community. And previously said, the basement of LYRA was built from GRAFT ICO money. If investors lose faith then it will be the SEC that will investigate. You really want that?

**Comment by RoggyDog** [comment]
Nice work. It states "Founders" within the document a few times. Who are these Founders? Appears Dan selects the Governing board and Advisory board but the Founders select the Supervisory board. Or is Dan the one and only remaining Founder?

**Comment by hardkano** [comment]
Founders will always be  Slava and Dan. Thanks for your contribution Roggy. I drafted it from an existing crypto in the top20. iota. Dan suggested me to modify the first election process instead of a formal setup by founders. he want to people apply and votes being made. I'm thinking how I will modify texts. if you have ideas go ahead.

**Comment by RoggyDog** [comment]
Election process will be tricky. First thing that comes to my mind is have candidates post a Graft SN address and have voters stake their Graft to the candidates SN addy they are voting for. Turn off SN rewards for the voting process and allow voters to place their votes(stakes) over the course of a week. At end of week those candidates with most Graft staked to their addy get elected.

Using Governing board as example, if we want 5 members and there are 20 candidates, a Graft holder would be able to divide their funds to the 5 candidates they'd like see get elected, or just put all their funds to one or a few to try and guarantee they get elected.

Just an off the top of my head idea to limit voting to actual Graft holders with as little coding or prep required. All we'd need is maybe a Github issue where only candidates post a small bio about themselves for Graft holders(voters) to choose from.

**Comment by hardkano** [comment]
For the vote/staking process i think we need to think about "traditionnal" way to do it in order to have only 1 vote per graft holder. Otherwise big pockets always win. And we need to think that process with the less coding required, because devs are volontered and would rather prefer working on development of the platforms than "voting process"

I like the idea of the github issues for candidates.

**Comment by RoggyDog** [comment]
I don't like the big pockets problem either but I can't think of how you can avoid it. What mechanism would be used to guarantee 1 vote per Graft holder when I can make as many wallets as I'd like and just pretend to be 50 different holders? I was just catching up on what happened with Steem/Steemit and that's a perfect example of why I'm hesitant in regards to DPOS and staking in general. But what's some other options?

**Comment by hardkano** [comment]
That's a good question. I will more look into that after I've done the bylaws. if you find anything meanwhile feel free to post it. we will need to cost before calling the election process

**Comment by yidakee** [comment]
@wizd 

> Lyra needs to run standalone. Graft needs to run standalone

Absolutely not. Lyra is a Graft product, as it was developed using Graft investor funds, by the ex-main Graft developer, pushed through the Graft project, and currently still featured on the Graft website, managed by Graft's PM (Dan) and github under Graft's control.

One Foundation, one community, different product segments. Be them tethered or not

**Comment by yidakee** [comment]
I disagree with 6.2

> The members of the Governing Board within the meaning of this section's paragraph 1 shall also be designated by the Founder Dan Itkis during his lifetime. The provisions in this section's paragraph 2 apply accordingly.

What this does is go back to old Graft nepotism, which is one of the biggest reasons Graft failed. Boris, who is Dan's brother, was one of the lead devs. Alona is Slava's daughter, also did work for Graft as Marketing and CM. And who knows what other relationships in the background, where the mismanaged ICO funds were used for. 

This, section, as described, is called an Autocracy, if one person has sole power to decide who other people may or may not vote on. I absolutely agree that Dan should source and select the first 3 candidates for mandates, but from there on not 1 person can have control of who is able to be voted into the Governing Board. Unless I misunderstood, this is an absolutely preposterous notion.

**Comment by hardkano** [comment]
@yidakee what you said is exactly what Dan suggested to change. I've done it and it is in the pull request for review. 

The first draft was took from iota and section 6 and after was almost not touch. I've done for a better Democratic purpose. feel free to give a look at the second one.

**Comment by yidakee** [comment]
Good to know @hardkano! Though I don't see any PR's, but trust these will be done. Work in progress, keep it up!

**Comment by hardkano** [comment]
Thats weird @yidakee i've done it yesterday night and its true i don,t see it today. Will do it right now.
